aboutevents/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.conf import settings
from django.views.generic  import RedirectView
from eventsapp.views import MainView,TagEventView,LatestEntriesFeed

admin.autodiscover()
from eventsapp.sitemap import EventSitemap

sitemaps = {'main':EventSitemap}

urlpatterns = patterns('',
    url(r'^robots.txt$', include('robots.urls')), 
    url(r'^$', MainView.as_view(),kwargs={'page':1}),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^events/', include('eventsapp.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login',{'template_name': 'eventsapp/login.html'},name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout',{'next_page': '/','template_name': 'eventsapp/logout.html'},name='logout'),
    url(r'^feed/$', LatestEntriesFeed()),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    
)
urlpatterns += patterns('django.contrib.staticfiles.views',url(r'^static/(?P<path>.*)$', 'serve'),)
urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
        }),)

urlpatterns+=staticfiles_urlpatterns()
urlpatterns += patterns('',
    url(r'^(?P<tag>[^/]+)/', TagEventView.as_view(),kwargs={'page':1}),
)

eventsapp/urls.py
from django.views.generic.base import TemplateView

__author__ = 'lex'
from django.conf.urls.defaults import patterns, include, url
from eventsapp.views import *
from eventsapp.sitemap import EventSitemap

urlpatterns = patterns('',
    url(r'^register_success/$',TemplateView.as_view(template_name='eventsapp/login_succes.html')),
    url(r'^wait_activation/$',TemplateView.as_view(template_name='eventsapp/wait_activation.html')),
    url(r'^page(?P<page>\d+)/$', MainView.as_view(),name='event-list'),
    url(r'^calendar/(?P<day>\d+)/(?P<month>\d+)/(?P<year>\d+)$', DateEventView.as_view(),name='calendar-event-list'),
    url(r'^calendar/(?P<month>\d+)/(?P<year>\d+)/$', CalendarView.as_view(),name='calendar-view'),
    url(r'^calendar/$', CalendarViewNow.as_view(),name='calendar-view-now'),
    url(r'^byuser/(?P<id>\d+)/page(?P<page>\d+)/', UsersEventView.as_view(),name='users-event-list'),
    url(r'^tag/(?P<tag>[^/]+)/page(?P<page>\d+)/', TagEventView.as_view(),name='tag-event-list'),
    url(r'^create/$',CreateEvent.as_view(),name='create-view'),
    url(r'^edit/(?P<pk>\d+)/$', EventUpdate.as_view(),name='edit-event-view'),
    url(r'^register/$',RegisterView.as_view(),name='register'),
    url(r'^activate_event/(?P<id>\d+)/$',ActivateEvent.as_view(),name='activate-event'),
    url(r'^activate_user/(?P<id>\d+)/$',ActivateUser.as_view(),name='activate-user'),
    url(r'^delete_event/(?P<id>\d+)/$',DeleteEvent.as_view(),name='delete-event'),
    url(r'^delete_user/(?P<id>\d+)/$',DeleteUser.as_view(),name='delete-user'),
    url(r'^moder/$',ModerView.as_view(),name='moder-view'),
    url(r'^admin_statistic/$',AdminView.as_view(),name='admin-view'),
    url(r'^profileedit/(?P<pk>\d+)/$', EditProfileView.as_view(),name='profile-edit'),
    url(r'^(?P<slug>[^/]+)\.html$',EventView.as_view(),name='detail-event-view'),
    url(r'^reviews/(?P<id>\d+)/$',CreateReview.as_view(),name='add-review'),
)

eventsapp/models.py
# coding: utf-8
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.db.models.signals import post_save,pre_save,pre_delete
import random
import string
import pytils
from datetime import datetime
from utils import *

def make_upload_poster_path(instance, filename):
    now = datetime.now().strftime('%Y/%m/%d/%H/%M/%S')
    ext = '.'+filename.split('.')[1]
    name = pytils.translit.slugify(filename)[:-len(ext)+1]+ext
    return u"upload/posters/%s/%s" % (now, name)

def make_upload_logo_path(instance, filename):
    now = datetime.now().strftime('%Y/%m/%d/%H/%M/%S')
    ext = '.'+filename.split('.')[1]
    name = pytils.translit.slugify(filename)[:-len(ext)+1]+ext
    return u"upload/logos/%s/%s" % (now, name)


class ServerSetting(models.Model):
    name = models.CharField(max_length=128, verbose_name=u'Опция',primary_key=True)
    value = models.BooleanField(verbose_name=u'Значение')

    def __unicode__(self):
        return self.name


class Country(models.Model):
    code = models.CharField(max_length=5)
    name = models.CharField(max_length=128)

    def __unicode__(self):
        return self.name


class Town(models.Model):
    name = models.CharField(max_length=128)
    country = models.ForeignKey(Country)

    def __unicode__(self):
        return self.country.name + " " + self.name


class Tag(models.Model):
    name = models.CharField(max_length=128,verbose_name=u'Название тега')

    def __unicode__(self):
        return self.name
    class Meta:
        verbose_name = u'Тег'
        verbose_name_plural = u'Теги'


class Event(models.Model):
    name = models.CharField(max_length=128,verbose_name=u'Название')
    date_start = models.DateField(verbose_name=u'Дата начала')
    date_end = models.DateField(verbose_name=u'Дата окончания')
    date_create = models.DateField(auto_now_add=True,verbose_name=u'Дата создания')
    description = models.TextField(verbose_name=u'Описание',default="")
    user = models.ForeignKey(User,verbose_name=u'Создатель')
    slug = models.SlugField(verbose_name=u'Слаг',null=True,blank=True,max_length=300)
    poster = models.ImageField(upload_to=make_upload_poster_path,verbose_name=u'Постер',null=True,blank=True)
    logo = models.ImageField(upload_to=make_upload_logo_path,verbose_name=u'Логотип',null=True,blank=True)
    tags = models.ManyToManyField(Tag,blank=True,null=True,verbose_name=u'Теги')
    accepted = models.BooleanField(default=False, verbose_name=u'Подверждена модератором')
    location = models.ForeignKey(Town, blank=True, null=True)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return  '/events/'+self.slug + '.html'
    class Meta:
        verbose_name = u'Событие'
        verbose_name_plural = u'События'

class Review(models.Model):
    name = models.CharField(max_length=128,verbose_name=u'Название')
    date_create = models.DateField(verbose_name=u'Дата создания')
    text = models.TextField(verbose_name=u'Текст')
    user = models.ForeignKey(User,verbose_name=u'Создатель')
    event = models.ForeignKey(Event,verbose_name=u'Событие')
    photo = models.ImageField(upload_to='upload/photos/%Y/%m/%d/%H/%M/%S/',blank=True,null=True,verbose_name=u'Фото')

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u'Рецензия'
        verbose_name_plural = u'Рецензии'


class UserProfile(models.Model):
    user = models.OneToOneField(User,verbose_name=u'Пользователь',null=True,blank=True)
    name = models.CharField(max_length=128,verbose_name=u'Имя',null=True,blank=True,default="")
    address = models.CharField(max_length=256,verbose_name=u'Адресс',null=True,blank=True,default="")
    phone = models.CharField(max_length=18,verbose_name=u'Телефон',null=True,blank=True,default="")
    description = models.TextField(verbose_name=u'Описание',null=True,blank=True,default="")
    photo_1 = models.ImageField(upload_to='upload/photos/%Y/%m/%d/%H/%M/%S/',blank=True,null=True,verbose_name=u'Фото')
    photo_2 = models.ImageField(upload_to='upload/photos/%Y/%m/%d/%H/%M/%S/',blank=True,null=True,verbose_name=u'Фото')
    photo_3 = models.ImageField(upload_to='upload/photos/%Y/%m/%d/%H/%M/%S/',blank=True,null=True,verbose_name=u'Фото')
    photo_4 = models.ImageField(upload_to='upload/photos/%Y/%m/%d/%H/%M/%S/',blank=True,null=True,verbose_name=u'Фото')
    photo_5 = models.ImageField(upload_to='upload/photos/%Y/%m/%d/%H/%M/%S/',blank=True,null=True,verbose_name=u'Фото')
    can_post = models.ManyToManyField('self', blank=True, null=True,symmetrical=False, related_name='journalists' )
    accepted = models.BooleanField(default=False, verbose_name=u'Подвержден модератором')
    moder = models.BooleanField(default=False, verbose_name=u'Пользователь является модератором')
    reviewer = models.BooleanField(default=False, verbose_name=u'Пользователь является рецензентом')
    moderate_user_events = models.BooleanField(default=True, verbose_name=u'Модерировать события пользователя')

    def thumb1(self):
        return get_thumbnail_url(self.photo_1.url,size=128)
    def thumb2(self):
        return get_thumbnail_url(self.photo_2.url,size=128)
    def thumb3(self):
        return get_thumbnail_url(self.photo_3.url,size=128)
    def thumb4(self):
        return get_thumbnail_url(self.photo_4.url,size=128)
    def thumb5(self):
        return get_thumbnail_url(self.photo_5.url,size=128)

    thumb1.short_description = 'thumb_photo1'
    thumb1.allow_tags = True
    thumb2.short_description = 'thumb_photo2'
    thumb2.allow_tags = True
    thumb3.short_description = 'thumb_photo3'
    thumb3.allow_tags = True
    thumb4.short_description = 'thumb_photo4'
    thumb4.allow_tags = True
    thumb5.short_description = 'thumb_photo5'
    thumb5.allow_tags = True
    def __unicode__(self):
        if self.name :
            return self.name
        else: return "None"

    class Meta:
        verbose_name = u'Профиль пользователя'
        verbose_name_plural = u'Профили пользователя'

def post_save_handler(sender, **kwargs):
    if kwargs['instance'].photo_1:create_thumbnail(kwargs['instance'].photo_1.path,size=128)
    if kwargs['instance'].photo_2:create_thumbnail(kwargs['instance'].photo_2.path,size=128)
    if kwargs['instance'].photo_3:create_thumbnail(kwargs['instance'].photo_3.path,size=128)
    if kwargs['instance'].photo_4:create_thumbnail(kwargs['instance'].photo_4.path,size=128)
    if kwargs['instance'].photo_5:create_thumbnail(kwargs['instance'].photo_5.path,size=128)


def pre_delete_handler(sender, **kwargs):
    if kwargs['instance'].photo_1:delete_thumbnail(kwargs['instance'].photo_1.path,size=128)
    if kwargs['instance'].photo_2:delete_thumbnail(kwargs['instance'].photo_2.path,size=128)
    if kwargs['instance'].photo_3:delete_thumbnail(kwargs['instance'].photo_3.path,size=128)
    if kwargs['instance'].photo_4:delete_thumbnail(kwargs['instance'].photo_4.path,size=128)
    if kwargs['instance'].photo_5:delete_thumbnail(kwargs['instance'].photo_5.path,size=128)


post_save.connect(post_save_handler, sender = UserProfile)
pre_delete.connect(pre_delete_handler, sender = UserProfile)

def fix_slug(sender, instance, raw, **kwargs):
    if isinstance(instance,Event):
        if not instance.slug or not instance.slug.strip():
            instance.slug = '_'.join((pytils.translit.slugify(instance.name),instance.date_start.strftime('%Y-%m-%d'),instance.date_end.strftime('%Y-%m-%d'),''.join(random.choice(string.ascii_uppercase + string.digits) for x in range(6))))

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

def fix_image_width(sender, instance, created, **kwargs):
    if isinstance(instance,Event):
        im = instance.poster
        if im:
            filename = str(im.path).decode('utf-8')
            image = Image.open(filename)
            pw = im.width
            ph = im.height
            if pw>760:
                koef = 760.0/float(pw)
                ph *= koef
                image = image.resize((760,int(ph)), Image.ANTIALIAS)
                image.save(filename)

def fix_photo_width(sender, instance, created, **kwargs):
    if isinstance(instance,UserProfile):
        im = instance.photo_1
        if im:
            filename = str(im.path)
            image = Image.open(filename)
            pw = im.width
            ph = im.height
            if pw>760:
                koef = 760.0/float(pw)
                ph *= koef
                image = image.resize((760,int(ph)), Image.ANTIALIAS)
                image.save(filename)
        im = instance.photo_2
        if im:
            filename = str(im.path)
            image = Image.open(filename)
            pw = im.width
            ph = im.height
            if pw>760:
                koef = 760.0/float(pw)
                ph *= koef
                image = image.resize((760,int(ph)), Image.ANTIALIAS)
                image.save(filename)
        im = instance.photo_3
        if im:
            filename = str(im.path)
            image = Image.open(filename)
            pw = im.width
            ph = im.height
            if pw>760:
                koef = 760.0/float(pw)
                ph *= koef
                image = image.resize((760,int(ph)), Image.ANTIALIAS)
                image.save(filename)
        im = instance.photo_4
        if im:
            filename = str(im.path)
            image = Image.open(filename)
            pw = im.width
            ph = im.height
            if pw>760:
                koef = 760.0/float(pw)
                ph *= koef
                image = image.resize((760,int(ph)), Image.ANTIALIAS)
                image.save(filename)
        im = instance.photo_5
        if im:
            filename = str(im.path)
            image = Image.open(filename)
            pw = im.width
            ph = im.height
            if pw>760:
                koef = 760.0/float(pw)

eventsapp/forms.py
# coding: utf-8
from django.contrib.auth.models import User
from datetime import *
__author__ = 'lex'
from django import forms
from eventsapp.models import Event,UserProfile,Review

class EventForm(forms.ModelForm):
    tags = forms.CharField(label=u'Теги')
    author = forms.IntegerField(widget=forms.HiddenInput(),required=False)
    def clean(self):
        if self.data['date_start'] and self.data['date_end']:
            if datetime.strptime(self.data['date_start'].replace('.','/')+" 00:00:00","%d/%m/%Y %H:%M:%S").date()>datetime.strptime(self.data['date_end'].replace('.','/')+" 00:00:00","%d/%m/%Y %H:%M:%S").date():
                raise forms.ValidationError(u"Даты не сходятся")
        return super(EventForm,self).clean()
    class Meta(object):
        model = Event
        exclude = ('user','slug','date_create', 'tags', 'location', 'accepted')


class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(
        label=u'Пароль еще раз',
        required=True,
        widget=forms.PasswordInput()
    )

    def clean(self):
        try:
            User.objects.get(username = self.data['username'])
            raise forms.ValidationError(u"Пользователь с таким логином уже зарегистрирован")
        except User.DoesNotExist:
            pass
        if self.data['password']!=self.data['password1']:
            raise forms.ValidationError(u"Пароли не совпадают")
        return super(RegisterForm,self).clean()

    class Meta:
        model = User
        fields =('username','password','email')
        widgets = {
            'password': forms.PasswordInput(),
            }
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        for key in self.fields:
            self.fields[key].required = True




class EditUserForm(forms.ModelForm):


    class Meta(object):
        model = UserProfile
        exclude = ('user', 'accepted', 'moder', 'can_post')


class ReviewForm(forms.ModelForm):
    author = forms.IntegerField(widget=forms.HiddenInput())
    class Meta(object):
        model = Review
        exclude = ('user','event','date_create')

aboutevents/templates/eventsapp/add_review.html
{% extends 'base.html' %}

{% block title %}Добавить рецензию{% endblock %}


{% block page_header %}
    <div class="page-header" xmlns="http://www.w3.org/1999/html">
        <h1>Добавить рецензию</h1>
    </div>
{% endblock %}
{% block content %}
    <br/>
    {%  if form.non_field_errors   %}
        <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">×</button>
            {{ form.non_field_errors  }}
        </div>
    {% endif %}

    <form method="post" action="." class="form-horizontal" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset >
            <div class="well">
    			<input type="hidden" name="author" id="id_author" value="{{ user.get_profile.id }}">
                <div class="row-fluid">
                    <div class="span4">
                        <div class="control-group{% if form.name.errors %} error {% endif %}">
                            <label class="control-label" for="id_name">Название</label>
                            <div class="controls" >
                                {{ form.name }}
                                <span class="help-inline">{% if form.name.errors %} {{ form.name.errors }}{% endif %}</span>
                            </div>
                        </div>
                    </div>
                    <div class="span5">
                        <div class="control-group {% if form.text.errors %} error {% endif %}">
                            <label class="control-label" for="id_text">Рецензия</label>
                            <div class="controls">
                                <textarea rows="8" style="width: 400px;" cols="280" name="text" id="id_text"></textarea>
                                <span class="help-inline">{% if form.text.errors %} {{ form.text.errors }}{% endif %}</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="control-group {% if form.photo.errors %} error {% endif %}">
                    <label class="control-label" for="id_photo">Фото</label>
                    <div class="controls">
                        {{ form.photo }}
                        <span class="help-inline">{% if form.photo.errors %} {{ form.photo.errors }}{% endif %}</span>
                    </div>
                </div>
                <div class="form-actions">
                    <button class="btn btn-primary" type="submit">Сохранить</button>
                </div>
            </div>
        </fieldset>
    </form>

{% endblock %}

aboutevents/templates/eventsapp/admin_view.html
{% extends 'base.html' %}

{% block title %}Интерфейс администратора{% endblock %}

{% block content %}
    {% if user.is_superuser %}
        {% if users %}
            <h3>Пользователи</h3>
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>
                        Пользователь
                    </th>
                    <th>
                        Событий
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for u in users %}
                    <tr>
                        <td><a href="/admin/auth/user/{{ u.id }}/">{{ u.username }}</a></td>
                        <td><a href="{% url activate-user u.id %}">{{ u.events_number }}</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}
    {% endif %}
{% endblock %}

aboutevents/templates/eventsapp/create_event.html
{% extends 'base.html' %}

{% block title %}Создать событие{% endblock %}


{% block page_header %}
    <div class="page-header" xmlns="http://www.w3.org/1999/html">
        <h1>Создать событие</h1>
    </div>
{% endblock %}
{% block content %}
    <br/>
    {%  if form.non_field_errors   %}
        <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">×</button>
            {{ form.non_field_errors  }}
        </div>
    {% endif %}

    <form method="post" action="." class="form-horizontal" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset >
            <div class="well">
                <div class="row-fluid">
                    <div class="span4">
                        <div class="control-group{% if form.name.errors %} error {% endif %}">
                            <label class="control-label" for="id_name">Название</label>
                            <div class="controls" >
                                {{ form.name }}
                                <span class="help-inline">{% if form.name.errors %} {{ form.name.errors }}{% endif %}</span>
                            </div>
                        </div>
                        <div class="control-group {% if form.date_start.errors %} error {% endif %}">
                            <label class="control-label" for="id_date_start">Дата начала события</label>
                            <div class="controls">
                                {{ form.date_start }}
                                <span class="help-inline">{% if form.date_start.errors %} {{ form.date_start.errors }}{% endif %}</span>
                            </div>
                        </div>
                        <div class="control-group {% if form.date_end.errors %} error {% endif %}">
                            <label class="control-label" for="id_date_end">Дата окончания события</label>
                            <div class="controls">
                                {{ form.date_end }}
                                <span class="help-inline">{% if form.date_end.errors %} {{ form.date_end.errors }}{% endif %}</span>
                            </div>
                        </div>
                        {% ifnotequal avaliable_authors|length 1%}
                            <label class="control-label" for="id_author">От чьего имени:</label>
                            <input type="hidden" name="author" id="id_author" value="{{ user.get_profile.id }}">
                            <div  class="control-group {% if form.author.errors %} error {% endif %}">
                                <div class="controls">
                                        {%  if user.is_authenticated %}
                                        <select id = "select_author" onchange="$('#id_author')[0].value = $('#select_author')[0].options[$('#select_author')[0].selectedIndex].value;">
                                            {% for u in avaliable_authors %}
                                                <option value="{{ u.id }}"
                                                        {% ifequal user.get_profile.id u.id %}
                                                            selected="selected">Моего</option>
                                                        {% else %}
                                                            >{% if  u.name%}
                                                                    {{ u.name }}
                                                            {% else %}
                                                                {{ u.user.username }}
                                                                {% endif %} 
                                                        {% endifequal %}
                                                </option>
                                            {% endfor %}
                                        </select>
                                        {% endif %}
                                        <span class="help-inline">{% if form.author.errors %} {{ form.author.errors }}{% endif %}</span>

                                </div>
                            </div>
                        {% endifnotequal %}
                    </div>
                    <div class="span5">
                        <div class="control-group {% if form.description.errors %} error {% endif %}">
                            <label class="control-label" for="id_description">Описание</label>
                            <div class="controls">
                                <textarea rows="8" style="width: 400px;" cols="280" name="description" id="id_description">{{ form.description.value }}</textarea>
                                <span class="help-inline">{% if form.description.errors %} {{ form.description.errors }}{% endif %}</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="control-group {% if form.poster.errors %} error {% endif %}">
                    <label class="control-label" for="id_poster">Постер</label>
                    <div class="controls">
                        {{ form.poster }}
                        <span class="help-inline">{% if form.poster.errors %} {{ form.poster.errors }}{% endif %}</span>
                    </div>
                </div>
                <div class="control-group {% if form.logo.errors %} error {% endif %}">
                    <label class="control-label" for="id_logo">Логотип</label>
                    <div class="controls">
                        {{ form.logo }}
                        <span class="help-inline">{% if form.logo.errors %} {{ form.logo.errors }}{% endif %}</span>
                    </div>
                </div>
                <div class="control-group {% if form.tags.errors %} error {% endif %}">
                    <label class="control-label" for="id_tags">Теги</label>
                    <div class="controls">
                        {{ form.tags }}
                        <span class="help-inline">{% if form.tags.errors %} {{ form.tags.errors }}{% endif %}</span>
                    </div>
                </div>
                <div class="form-actions">
                    <button class="btn  btn-primary" type="submit">Сохранить</button>
                </div>
            </div>
        </fieldset>
    </form>

{% endblock %}

aboutevents/templates/eventsapp/edit_profile.html
{% extends 'base.html' %}

{% block title %}Профиль{% endblock %}


{% block page_header %}
    <div class="page-header" xmlns="http://www.w3.org/1999/html">
        <h1>Редактировать профиль</h1>
    </div>
{% endblock %}
{% block content %}
    <br/>
    {%  if form.non_field_errors   %}
        <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">×</button>
            {{ form.non_field_errors  }}
        </div>
    {% endif %}

    <form method="post" action="." class="form-horizontal" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset >
            <div class="well">
                <div class="row-fluid">
                    <div class="span4">
                        <div class="control-group">
                            <label class="control-label" for="id_name">Имя</label>
                            <div class="controls" style="width: 460px;">
                                {{ form.name }}
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="id_address">Адресс</label>
                            <div class="controls">
                                {{ form.address }}
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="id_phone">Контактный телефон</label>
                            <div class="controls">
                                {{ form.phone }}
                            </div>
                        </div>
                    </div>
                    <div class="span5">
                        <div class="control-group">
                            <label class="control-label" for="id_description">Описание</label>
                            <div class="controls">
                                <textarea rows="8" style="width: 400px;" cols="280" name="description" id="id_description">{{ form.description.value }}</textarea>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="id_photo_1">Фото</label>
                    <div class="controls">
                        {{ form.photo_1 }}
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="id_photo_2">Фото</label>
                    <div class="controls">
                        {{ form.photo_2 }}
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="id_photo_3">Фото</label>
                    <div class="controls">
                        {{ form.photo_3 }}
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="id_photo_4">Фото</label>
                    <div class="controls">
                        {{ form.photo_4 }}
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="id_photo_5">Фото</label>
                    <div class="controls">
                        {{ form.photo_5 }}
                    </div>
                </div>

                <div class="form-actions">
                    <button class="btn btn-primary" type="submit">Сохранить</button>
                </div>
            </div>
        </fieldset>
    </form>

{% endblock %}

aboutevents/templates/eventsapp/form.html
{% extends 'base.html' %}


{% block title %}Редактировать событие{% endblock %}

{% block content %}
    <form action="." method="post" class="form-horizontal" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset>
            {{ form.as_p }}
    </fieldset>
    <button class="btn" type="submit">Сохранить</button>
    </form>
{% endblock %}

aboutevents/templates/eventsapp/login.html
{% extends 'base.html' %}

{% block title %}Вход{% endblock %}


{% block page_header %}
<div class="page-header">
    <h1>Авторизация</h1>
</div>
{% endblock %}
{% block content %}
    <br/>
    {% if form.errors %}

        <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>Неверный логин или пароль !</strong>
        </div>
    {% endif %}

    <form method="post" action="{% url django.contrib.auth.views.login %}" class="form-horizontal">
    {% csrf_token %}
        <fieldset>
            <div class="well">
                <div class="control-group">
                    <label class="control-label" for="id_username">Логин</label>
                    <div class="controls">
                        {{ form.username }}
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="id_password">Пароль</label>
                    <div class="controls">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-actions">
                    <button class="btn" type="submit">Войти</button>
                </div>
                <input type="hidden" name="next" value="{{ next }}" />
            </div>
        </fieldset>
    </form>

{% endblock %}

aboutevents/templates/eventsapp/logout.html
{% extends 'base.html' %}

{% block title %}До свидания{% endblock %}

{% block content %}

   {{ title }}

{% endblock %}